name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"


jobs:
  build-stable:
    strategy:
      fail-fast: false
      matrix:
        features: [
          '-F device_neokey_1x4',
          '-F device_neorotary4',
          '-F device_neoslider',
          '-F device_rotary_encoder',
        ]
    name: Build & Lint (Default Features, Stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --component clippy
      - run: cargo build --no-default-features ${features}
      - run: cargo clippy --no-default-features ${features}

  build-nightly:
    strategy:
      fail-fast: false
      matrix:
        features: [
          '-F device_arcade_button_1x4',
          '-F device_neokey_1x4,module_neopixel',
          '-F device_neorotary4,module_neopixel',
          '-F device_neoslider,module_neopixel',
          '-F device_neotrellis',
          '-F device_neotrellis,module_neopixel',
          '-F device_rotary_encoder,module_neopixel',
        ]
    name: Build & Lint With Features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install nightly --component clippy
      - run: rustup default nightly
      - run: cargo build --no-default-features ${features}
      - run: cargo clippy --no-default-features ${features}
